/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReposIndexRouteImport } from './routes/repos.index'
import { Route as ReposOwnerNameRouteImport } from './routes/repos.$owner.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerNameRoute = ReposOwnerNameRouteImport.update({
  id: '/repos/$owner/$name',
  path: '/repos/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/repos/': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/repos': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/repos/': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agents'
    | '/models'
    | '/settings'
    | '/setup'
    | '/repos/'
    | '/repos/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agents'
    | '/models'
    | '/settings'
    | '/setup'
    | '/repos'
    | '/repos/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agents'
    | '/models'
    | '/settings'
    | '/setup'
    | '/repos/'
    | '/repos/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentsRoute: typeof AgentsRoute
  ModelsRoute: typeof ModelsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ReposIndexRoute: typeof ReposIndexRoute
  ReposOwnerNameRoute: typeof ReposOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$name': {
      id: '/repos/$owner/$name'
      path: '/repos/$owner/$name'
      fullPath: '/repos/$owner/$name'
      preLoaderRoute: typeof ReposOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentsRoute: AgentsRoute,
  ModelsRoute: ModelsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ReposIndexRoute: ReposIndexRoute,
  ReposOwnerNameRoute: ReposOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
